name: CI/CD - Docker Branch Test

# Déclenchement manuel
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'Docker'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Récupérer le code depuis la branche choisie
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch }}

    # 2. Installer Java (17 par exemple)
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # 3. Build le projet avec Maven
    - name: Build with Maven
      run: mvn clean package

    - name: Créer le fichier recheconnectFirebase.json
      run: echo '${{ secrets.FIREBASE_CONFIG }}' > /tmp/rucheconnectFirebase.json

    - name: Exporter la variable d'environnement
      run: echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/rucheconnectFirebase.json" >> $GITHUB_ENV

    - name: Lancer les tests (avec Firebase creds)
      run: mvn test
    - name: Vérifier que la variable GOOGLE_APPLICATION_CREDENTIALS est bien définie
      run: |
        if [ -z "$GOOGLE_APPLICATION_CREDENTIALS" ]; then
          echo "❌ La variable GOOGLE_APPLICATION_CREDENTIALS n'est PAS définie !"
          exit 1
        else
          echo "✅ GOOGLE_APPLICATION_CREDENTIALS est définie : $GOOGLE_APPLICATION_CREDENTIALS"
        fi
        
    # 4. Lancer les tests unitaires
    - name: Run tests
      run: mvn test
    - name: Générer rapport tests JUnit
      run: mvn surefire-report:report

    # 5. (Optionnel) Build l’image Docker si tu veux tester Docker
    # - name: Build Docker image
    #   run: docker build -t myapp:latest .
